# SPDX-FileCopyrightText: 2026 Andrew Zhang <whisper67265@outlook.com>
#
# SPDX-License-Identifier: BSL-1.0
#
extends: default

rules:
  # Matches common GitHub Actions style and language-formatters pretty-format-yaml.
  document-start: disable
  truthy:
    check-keys: false
  indentation:
    indent-sequences: false
  line-length:
    max: 120
